import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { KPIMetrics } from './excel-utils';

export const exportToPDF = async (kpis: KPIMetrics, companyName: string = 'Your Company') => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Header
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('FinArrow', 20, 20);
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(companyName, 20, 28);
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 60, 20);
  
  // Title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Investor Report', 20, 45);
  
  // Executive Summary
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Executive Summary', 20, 60);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  let yPos = 70;
  const lineHeight = 8;
  
  // Key metrics
  const metrics = [
    { label: 'Monthly Recurring Revenue (MRR)', value: `$${kpis.mrr.toLocaleString()}`, change: kpis.mrrChange },
    { label: 'Customer Acquisition Cost (CAC)', value: `$${kpis.cac.toFixed(2)}`, change: kpis.cacChange },
    { label: 'Churn Rate', value: `${kpis.churnRate.toFixed(1)}%`, change: kpis.churnChange },
    { label: 'Net Burn Rate', value: `$${kpis.burnRate.toLocaleString()}`, change: kpis.burnRateChange },
    { label: 'Runway', value: `${kpis.runwayMonths.toFixed(1)} months`, change: 0 },
    { label: 'LTV/CAC Ratio', value: kpis.ltvCacRatio.toFixed(2), change: kpis.ltvCacChange },
    { label: 'ARPU', value: `$${kpis.arpu.toFixed(2)}`, change: kpis.arpuChange },
  ];
  
  metrics.forEach((metric) => {
    pdf.setFont('helvetica', 'bold');
    pdf.text(metric.label, 20, yPos);
    
    pdf.setFont('helvetica', 'normal');
    pdf.text(metric.value, 120, yPos);
    
    if (metric.change !== 0) {
      const changeText = `${metric.change > 0 ? '+' : ''}${metric.change.toFixed(1)}%`;
      if (metric.change > 0) {
        pdf.setTextColor(16, 185, 129);
      } else {
        pdf.setTextColor(239, 68, 68);
      }
      pdf.text(changeText, 160, yPos);
      pdf.setTextColor(0, 0, 0);
    }
    
    yPos += lineHeight;
  });
  
  // Key Insights
  yPos += 10;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Key Insights', 20, yPos);
  
  yPos += 10;
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  const insights = [
    `• Monthly Recurring Revenue is ${kpis.mrrChange > 0 ? 'growing' : 'declining'} at ${Math.abs(kpis.mrrChange).toFixed(1)}% MoM`,
    `• LTV/CAC ratio of ${kpis.ltvCacRatio.toFixed(2)} ${kpis.ltvCacRatio > 3 ? 'exceeds' : 'is below'} the healthy benchmark of 3.0`,
    `• Current runway of ${kpis.runwayMonths.toFixed(1)} months ${kpis.runwayMonths > 6 ? 'provides comfortable' : 'requires attention to'} runway`,
    `• Churn rate at ${kpis.churnRate.toFixed(1)}% ${kpis.churnRate < 5 ? 'is healthy' : 'may need improvement'}`,
  ];
  
  insights.forEach((insight) => {
    pdf.text(insight, 20, yPos);
    yPos += lineHeight;
  });
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by FinArrow - From spreadsheet chaos to investor clarity', 20, pageHeight - 10);
  
  // Save PDF
  const fileName = `FinArrow_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(fileName);
};
